### ISSUE TITLE
Is the GM02S pre-loaded firmare Nb-Iot enabled?

### ISSUE THREAD

**Issue by tomy983** [microchip-pic-avr-solutions/avr-iot-cellular-arduino-library#1]
Hello, I would like to use this module in a country with only Nb-Iot coverage and with a different sim card than the one that comes with the kit. Is this possible?
Thank you

**Comment by johanlofstad** [comment]
Yes and no. At the time of writing, the board only supports LTE-M. Support for NB-IoT will come in an upcoming firmware patch later, as the Sequans Monarch GM02S doesn't support it as of yet. That being said, you are free to use a SIM card from any provider.

**Comment by tomy983** [comment]
Is there anywhere in the documentations where I can find this information? All I can find on the Microchip website is that the board actually supports NB-IoT connectivity (which is a false statement). 
When is the firmare patch with NB-IoT connectivity release is planned for?
Thank you.
