### ISSUE TITLE
Log formatting for float doesn't work

### ISSUE THREAD

**Issue by SeanCairns** [microchip-pic-avr-solutions/avr-iot-cellular-arduino-library#10]
The documentation seems to indicate that I can use c++ printf formatting with Log. For example:
```
float myFloat = 3.14f;
Log.infof("Test float: %f", myFloat);
```
Should output:
`[INFO] Test float: 3.14 `

Instead I get:
`[INFO] Test float: ? `

**Comment by M65649** [comment]
Hello,

Could you attempt with enabling the option for ´Full print support´ in `Tools` -> `print()` in the Arduino IDE and test again?

**Comment by SeanCairns** [comment]
That works! And makes debugging A LOT easier. Thanks again!

**Comment by M65649** [comment]
No problem. I'll append that to our documentation page for the log module.
