### ISSUE TITLE
sandbox example resetInterrupt() mistake

### ISSUE THREAD

**Issue by Nefarious19** [microchip-pic-avr-solutions/avr-iot-cellular-arduino-library#11]
![image](https://user-images.githubusercontent.com/21359680/224827395-d69f0c16-f847-463d-bb91-75817c8a1531.png)
 This does not have sense. 
PORTD.INTFLAGS = PIN2_bm; will never be executed.
I suggest to change both handlers as below:

![image](https://user-images.githubusercontent.com/21359680/224827674-5f879703-137f-46af-aecb-f35bdc6ed97f.png)

**Comment by M65649** [comment]
Thanks, good catch, we’ll fix it in the next release.

**Comment by M65649** [comment]
This is now fixed in release 1.3.6.
