### ISSUE TITLE
Arduino Client interface ?

### ISSUE THREAD

**Issue by tavdog** [microchip-pic-avr-solutions/avr-iot-cellular-arduino-library#21]
Is there a way to use this library as a Client object in arduino ?  I realize that TinyGSM client does seem to support sequans monarch but it would be nice to be able to use this library as a Client in alongside other libraries that implement client interface.

**Comment by M65649** [comment]
Hello @tavdog,

Are you referering to something like this: https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Client.h?

That’s not something that’s implemented in the library at the moment. Could you elaborate more on your usecase? 

Best,
Simen

**Comment by tavdog** [comment]
I have a device that can run on WiFi or Cellular.  My arduino based software interfaces with the WiFi or cell chip via the Client interface.  For the software to be able to switch which modem is uses at runtime they both need to be treated as a client.

**Comment by M65649** [comment]
I understand. Are you using the AVR-IoT Cellular Mini? Which wifi modem are you using and how is it connected? Are you using MQTT, HTTP or raw sockets?

**Comment by tavdog** [comment]
Yes I have the AVR-iot cellular mini board (https://www.microchip.com/en-us/development-tool/ev70n78a) . My devices uses both http and mqtt.

**Comment by M65649** [comment]
Hello, unfortunately there are no examples with the board and TinyGSM. That said, I don’t see any problem using TinyGSM if you just use their existing implementation for the Sequans modem.

**Comment by tavdog** [comment]
Yes I tried that but I can't get it to work. I'm just guessing as to which pins to use.

**Comment by M65649** [comment]
Hello, the USART is USART1 and the flow control pins are on PC7 & PC4. You can find more information here: https://ww1.microchip.com/downloads/en/DeviceDoc/AVR-IoT-Cellular-Mini-HW-UserGuide-DS50003320.pdf. So you need to set the SerialAT as Serial1 at least. I’m not completely sure how TinyGSM does flow control however.

**Comment by M65649** [comment]
Hello @tavdog,

Have you managed to use the tinyGSM library with the board?

**Comment by tavdog** [comment]
No i haven't been able to use it.  The pins don't work.

**Comment by M65649** [comment]
Could you show what you've tried so far and do you know if tinyGSM uses flow control for the UART communication? I'm afraid that supporting interaction with libraries such as tinyGSM is not something we can prioritize highly and will rather be on a community based effort.

**Comment by tavdog** [comment]
here is are the pin definitions I tried using.
`#define MODEM_RST            PIN_PC5
// #define MODEM_PWRKEY         -1
// #define MODEM_POWER_ON       -1
#define MODEM_TX             PIN_PC0
#define MODEM_RX             PIN_PC1
#define MODEM_RTS            PIN_PC7
#define MODEM_CTS            PIN_PC4

//#define MODEM_DTR            32
//#define MODEM_RI             33

  SerialMon.println("Wait...");

  // Set GSM module baud rate
  //TinyGsmAutoBaud(SerialAT, GSM_AUTOBAUD_MIN, GSM_AUTOBAUD_MAX);
  SerialAT.begin(115200);
  delay(6000);

  // Restart takes quite some time
  // To skip it, call init() instead of restart()
  SerialMon.println("Initializing modem...");
  modem.restart();
  // modem.init();

  String modemInfo = modem.getModemInfo();
  SerialMon.print("Modem Info: ");
  SerialMon.println(modemInfo);
`

**Comment by M65649** [comment]
And how are the defines used? How does e.g. the tinyGSM library use the reset pin to reset the modem? I can't see any use of these defines in the examples from tinyGSM. I guess if tinyGSM does not use flow control you can just keep the RTS line low all the time as a slight hack. 

Other than that, you can look at the startup code in the library to get an idea of the startup procedure: https://github.com/microchip-pic-avr-solutions/avr-iot-cellular-arduino-library/blob/1a494e714f1a57ae736a3d7e447e758595e49544/src/sequans_controller.cpp#L499

**Comment by tavdog** [comment]
Here is the tinygsm library sequans driver https://github.com/vshymanskyy/TinyGSM/blob/master/src/TinyGsmClientSequansMonarch.h

**Comment by M65649** [comment]
Looks like it doesn't do anything with the reset pin or flow control. I would advice to at least toggle the reset pin and set RTS low before you initialize tinyGSM.
