### ISSUE TITLE
using with PlatformIO

### ISSUE THREAD

**Issue by tavdog** [microchip-pic-avr-solutions/avr-iot-cellular-arduino-library#22]
I did the leg work to get this board working in platformio. Here is the platformio.ini file that allowed me to compile the mqtt example for this board 

```[env:avr_iot]
platform = atmelmegaavr
board = AVR64DB48
upload_protocol = pkobn_updi
upload_flags = -F
framework = arduino
lib_deps = 
    https://github.com/microchip-pic-avr-solutions/avr-iot-cellular-arduino-library```

I also had to add #include <Wire.h> in at the top of the file just below Arduino.h

**Comment by M65649** [comment]
Hello,

Thanks, we’ll have a look at this.

**Comment by tavdog** [comment]
Thanks. Might be useful to include the platformio.ini file in the repo for others to use.
