### ISSUE TITLE
PORTC ISR not happy when DxCore is using other PORT interrupts

### ISSUE THREAD

**Issue by echoromeo** [microchip-pic-avr-solutions/avr-iot-cellular-arduino-library#3]
https://github.com/microchip-pic-avr-solutions/avr-iot-cellular-arduino-library/blob/c0fb29a07bc384753248f7c7011930b6d3910d7a/src/sequans_controller.cpp#L161

The ISR for PORTC_PORT_vect will cause a compile error when also using other pin interrupts. See https://github.com/SpenceKonde/DxCore/blob/master/megaavr/extras/Ref_Interrupts.md

I suggest changing the code to use attachInterrupt().

Issue found when adding the adafruit gps library to one of the examples.

**Comment by johanlofstad** [comment]
Fixed in 1.2.0 

https://github.com/microchip-pic-avr-solutions/avr-iot-cellular-arduino-library/releases/tag/1.2.0
